profil = ["Profile 7", "Profile 8", "Profile 9", "Profile 10", "Profile 11",
		  "Profile 13", "Profile 14", "Profile 109", "Profile 118", "Profile 119"]

nama = [
    "Ali Hasanudin",
    "Riskia Ayu Febrianti",
    "Budi Prasetyo Wibowo",
    "Aryo Nugraha",
    "Nana Annisa",
    "Yahya Nugraha",
    "Putri Kirana Dewi",
    "Nanda Marsa Ayunda",
    "Yudi Pradanawan",
    "Mutia Ayu Nur",

    "Bayu Danang Merta",
    "Bellanda Clara Ayunda ",
    "Budi Suryanto",
    "Miranda Nella",
    "Sadewa Lingga Budiantoro",
    "Alffianto Kuntoro",
    "Annisa Chania",
    "Fattahilah Sadewa",
    "Diah Ayu Cindy",
    "Yuli Ayunda Dewi",

    "Azzarin Ristia Nabila",
    "Fabian Nadeo Putra",
    "Nia EKa Yuliana",
    "Bayu Dwiganara",
    "Syifa Radifah",
    "Aditya Derdinand",
    "Siti Fauziyah",
    "Reyhan Utomowa",
    "Salma Arowaya",
    "Attaka Majid",

    "Putri Keancana",
    "Raja Putra Wardanawan",
    "Affifah Rahman Nabila",
    "Shaka Kurnia Wijaya",
    "Cynara Nafisah",
    "Mona Hadfinna",
    "Mahendra Rhejaa Fadilah",
    "Fryshta Eka Nabilla",
    "Yanuar Suryadi",
    "Angga Siregar Putra",

    "Sutisna Ayuni",
    "Ayu Yulistya Ningsih",
    "M. Putra Susanto",
    "Nayla Chelsea Anggita",
    "Putra Rudi Wirawan Nurbakti",
    "Fani Cintya A",
    "Rasya Gibran Sulistyo",
    "M. Fadil Achmad",
    "Delima Ariesta",
    "Rayhan Adi Wicasa",

    "Muhammad Iqbal Ramadhan",
    "Bagas Putra Ariel",
    "Afifah Renu Hasanah",
    "Reno Naufal Wijaya",
    "Putri Agustina Wahyuni",
    "Syifa Putri Ramadhani",
    "Muhammad Nur Faqih Mahmud",
    "Jesica Putri Ayu Deviana",
    "Immada Clarissa Putri Anjani",
    "Rayhan Cakra Lesmana",

    "Cintya Cindy Ayu Nissa",
    "Bella Nur Rahma",
    "Budi Ahmad Putra Laksa",
    "Cilla Cintya Chania",
    "M. Irsyad Gunawan Agung",
    "Fikri Budi Ramadhan",
    "Indah Budi Pratiwi",
    "Intan Putri Aprillia",
    "Rensky Maulana Ibrahim",
    "Achmad Billy Maulana",

    "Paradista Chania Aysala",
    "Tiara Andini Azzizah",
    "Yoga Syahrul Anugrah",
    "Bella Permata Sari",
    "Rifky Wahyu Saputra",
    "Fadhil Achmad Saputro",
    "Arya Perdana Kusuma Wicasa",
    "Siti Rahma Aulia Sarah",
    "Aldi Maulana Akbar",
    "Franky Kusuma Adelardo",

    "Rayhan Bagus Ghifari",
    "Marshanda Clarista Putri Bianca",
    "Muhammad Gilang Ramadhan",
    "Anggraeni Ratna Safitri",
    "Kayla Naisya Faradila",
    "Safa Fitri Aulia",
    "Famelya Anggita Novianti",
    "Revan Malik Ibrahim",
    "Adriansyah Qolbi Muhammad",
    "Nadilla Carina Fionita",

    "Rayhan Ferdinand",
    "Mustofa Daniel Arya",
    "Naufal Akhmal Wijayanto",
    "Septian Andini Fitria",

    "Mikha Ilyasa Agung",

    "Kristiani Livia Viadgianti",
    "Gizella Anastya Syakhira",
    "M. Putra Hartanto",
    "Zaaka Billy Badrurahman",
    "Muhammad Septyo Agung Mahmud",
]

kelamin = [
    0,1,0,0,1,0,1,1,0,1,
    0,1,0,1,0,0,1,0,1,1,
    1,0,1,0,1,0,1,0,1,0,
    1,0,1,0,1,1,0,1,0,0,
    0,1,0,1,0,1,0,0,1,0,
    0,0,1,0,1,1,0,1,1,0,
    1,1,0,1,0,0,1,1,0,0,
    1,1,0,1,0,0,0,1,0,0,
    0,1,0,1,1,1,1,0,0,1,
    0,0,0,1,0,1,1,0,0,0,
]

email = [
    "alihasn.01.10@gmail.com",
    "risfebri11@gmail.com",
    "budprasety@gmail.com",
    "aryonugh@gmail.com",
    "nanissa0110@gmail.com",
    "yahnugrah@gmail.com",
    "putriptr0110@gmail.com",
    "nandayundaa1@gmail.com",
    "yudipradan01@gmail.com",
    "mtianur001@gmail.com",

    "byumerta1@gmail.com",
    "Bellandayu01@gmail.com",
    "budsuryant01@gmail.com",
    "nela.mirra@gmail.com",
    "dwa.lingga10@gmail.com",
    "alffiantoro@gmail.com",
    "annicsaa@gmail.com",
    "fataahxdewa@gmail.com",
    "diahcindy03@gmail.com",
    "yulayund1@gmail.com",

    "azzarinrst@gmail.com",
    "fabiannadeo@gmail.com",
    "niaejuliana@gmail.com",
    "bayudwiganara@gmail.com",
    "syifaradifah@gmail.com",
    "aditferdinanda@gmail.com",
    "sitifauziyyahh@gmail.com",
    "reyhanutomowa@gmail.com",
    "salmaarowaya@gmail.com",
    "attakmajid@gmail.com",

    "putrikeancana@gmail.com",
    "rajawardanawan@gmail.com",
    "affifahh7@gmail.com",
    "shakapwijaya@gmail.com",
    "cynnarafisa@gmail.com",
    "monahfnna87@gmail.com",
    "mahendrejaa@gmail.com",
    "fryshta.eka823@gmail.com",
    "yanrasuryad@gmail.com",
    "anggasiregarp@gmail.com",

    "sutisnayun@gmail.com",
    "ayulistyaan@gmail.com",
    "muhh.santosoo@gmail.com",
    "nahychelsee@gmail.com",
    "rudinurbaktii01@gmail.com",
    "raafnii@gmail.com",
    "rcuulii@gmail.com",
    "fadiljaiduni@gmail.com",
    "ariestyadelima@gmail.com",
    "rahannadi1@gmail.com",

    "iqbalra2507@gmail.com",
    "renuwuxtrouble@gmail.com",
    "renuwuxbackup@gmail.com",
    "bagasa.ariel07@gmail.com",
    "rhanlesmna@gmail.com",
    "syifa.ayu.08.01.01@gmail.com",
    "m.nurfaqmah@gmail.com",
    "jesicadeviana5@gmail.com",
    "immadaputri@gmail.com",
    "rhanlesmna@gmail.com",

    "cyntttayu@gmail.com",
    "bella.rahhma@gmail.com",
    "budilalaksa@gmail.com",
    "cilaaaciaaa1@gmail.com",
    "irsygunagung@gmail.com",
    "fikr.ramadh@gmail.com",
    "indahbudpratiwiii@gmail.com",
    "intanputaprillia@gmail.com",
    "renuwuxrensky@gmail.com",
    "achmadmaullana01@gmail.com",

    "paradistaaysala@gmail.com",
    "tiarraazizahh@gmail.com",
    "yogaanuggrohoo@gmail.com",
    "bellaaperrmataa@gmail.com",
    "rifkhyywahyu@gmail.com",
    "fadhilllsaputro@gmail.com",
    "aryyaaperdanaa@gmail.com",
    "sitirahmaaulia240@gmail.com",
    "aldimaulanaakbar00@gmail.com",
    "frankyadelardo@gmail.com",

    "ghifarirayhan79@gmail.com",
    "marshandab47@gmail.com",
    "gilangrahmadhn5@gmail.com",
    "anggraeenirattnaa@gmail.com",
    "kaylanayafara@gmail.com",
    "safafayuli@gmail.com",
    "famelya86@gmail.com",
    "revanamaliq@gmail.com",
    "adriansyah.sutejo31@gmail.com",
    "nadilacarina3@gmail.com",

    "hanrey.ipur@gmail.com",
    "musfhatata@gmail.com",
    "nopal.akmal61@gmail.com",
    "septiantaurus@gmail.com",
    "mikhailya96@gmail.com",

    "kristianiliviadg@gmail.com",
    "gizelaptriyaa@gmail.com",
    "muhmadputra15@gmail.com",
    "zakkyrahman1131@gmail.com",
    "muhamm.sptyp@gmail.com",
]

namaTaufiq = [
    "Yuli Setiawan",
    "Eko Wijaya",
    "Yuni Nafisah",
    "Prita agustina",
    "Naufal Ardiansyah",
    "Hana Anissa Herian",
    "Heraldy Gunawan",
    "Eka Wahyu",
    "Bagus Rahmad",
    "Budi Santoso",

    "Dwi Panca",
    "faradilla nina",
    "Erfina Pratiwi",
    "Yazid Hasbilluh Kurniawan",
    "Bagus Hariawan",
    "Josephine Anindya",
    "Sarah Husaini",
    "Shabir Maulana",
    "Olivia Niken",
    "Gita Permata",

    "Argo Prasetyawan",
    "Salma Azizah",
    "Faradilla Aulia",
    "Dimas Wahyu",
    "Regina April",
    "Agis Prasetya",
    "Ardy Riski",
    "Muhammad Fadlan",
    "Septinia Kurniawan",
    "Damar Eka",

    "Fredinan Puan",
    "Amanda Bella Putri",
    "Bambang Suhatmoyo",
    "Kairaini Aliesa",
    "Lika Arletta",
    "Arjuna Ghafur",
    "Damar Hafidzhuan",
    "Lista Kamilla",
    "Sadiva Pratiwi",
    "Hermanto Caisar",

    "Windy Cantika",
    "Stephani Amanda Safitri",
    "Ardyanto Putra Wardhana",
    "Caroline Putri",
    "Nabil Saputra",
    "Khansa Azzahra",
    "Naufal Azwin",
    "Riska Rahmawati",
    "Rohmat Ubaidillah",
    "Setiawan Nugraha",

    "Anastasya Raisha",
    "Rakha Bumi",
    "Fikky Devano Purwanto",
    "Lesmana Dewa",
    "Ilyasa Fadil",
    "Belinda Inggridina Amelia",
    "Putri Bella Kartika",
    "Meydina Margaretha",
    "Muhammad Wawan",
    "Budiman Yahya Pradana",

    "Yahya Budiman",
    "Farhan Nurrahman",
    "Sisca Pratiwi",
    "Ahmad Fioren",
    "Alif Ramadhan",
    "Divani Permatasari",
    "Angga Dewangga",
    "Sasya Putri",
    "Selma Nabila Hayati",
    "Iwan Setiawan",

    "Rafi Fadhil Athalla",
    "Jonathan Putra",
    "Karina Aulia",
    "Diyastra Mahendra",
    "Agung Prasetya",
    "Aulia Lita Hani",
    "Sifa Nada",
    "Hani Salsabila",
    "Denis Prasetya kurniawan",
    "Griska Adelina Septinia",

    "Niara Rahmadhani",
    "Fajar Wijaya",
    "Anissha Fitrianni",
    "Galih Wibowo",
    "Rahma Aulia",
    "Maya Dewi",
    "Dhesy Lestari",
    "Rizky Firdaus",
    "Ditho Prasetyo",
    "Amanda Putri",

    "Karina Tiyas",
    "Abhista Deana",
    "Juana Noelle",
    "Jasmine Hanura",
    "Santiawati Agustina",
    "Pawitri Sari",
    "Yusti Fanggraeni",
    "Pamela Audine",
    "Anisha Pranaya",
    "Keita Pramudya",

    "Haris Cristopher",
    "Sinta Cintia",
    "Toni Sucipto",
    "Hani Baharani",
    "Ruli Abdhi",
    "Vidi Pratama",
    "Azzahra Fitriana",
    "Ilham Maulana",
    "Mayya Fitri",
    "Romadhon Ramzy",
]

emailTaufiq = [
    "yulisetiawan746@gmail.com",
    "ekow05047@gmail.com",
    "yuninafisah9@gmail.com",
    "agustinaprita304@gmail.com",
    "naufalardiansyah651@gmail.com",
    "hanaanissa33@gmail.com",
    "heraldygunawan@gmail.com",
    "ekawahy099@gmail.com",
    "bagusrahmad262@gmail.com",
    "budisantos0@gmail.com",

    "dwipancaa65@gmail.com",
    "f.ninadilaa@gmail.com",
    "erfinpp34@gmail.com",
    "yahhszid@gmail.com",
    "bagushari931@gmail.com",
    "jose.anindya@gmail.com",
    "srhhusaini@gmail.com",
    "shabirmaulana23@gmail.com",
    "ooliviya96@gmail.com",
    "permatagita588@gmail.com",


    "argopraz@gmail.com",
    "azizahsalma237@gmail.com",
    "faradillaaulia62@gmail.com",
    "dimaswahyu4769@gmail.com",
    "aprilregina663@gmail.com",
    "agisprasetya171@gmail.com",
    "arddyriski@gmail.com",
    "fadlaanm24@gmail.com",
    "kurniaseptinia@gmail.com",
    "damarek099@gmail.com",

    "freddinan35@gmail.com",
    "manndabeel99@gmail.com",
    "bambang.suhatmoyo@gmail.com",
    "aliesakairaini@gmail.com",
    "lika.arletta@gmail.com",
    "arjuna.gh9@gmail.com",
    "dhafidzuann@gmail.com",
    "listakamila299@gmail.com",
    "sadivapratiwi0@gmail.com",
    "hermantocaisar@gmail.com",

    "windycantika13@gmail.com",
    "stephaniamanda67@gmail.com",
    "ardyantoputra43@gmail.com",
    "carolineerindra@gmail.com",
    "saputranabil157@gmail.com",
    "azzahrakhansa006@gmail.com",
    "naufalazwin85@gmail.com",
    "riskarahmawati400@gmail.com",
    "rohmatubaidillah3@gmail.com",
    "setiawannugraha372@gmail.com",

    "raishaanastasya003@gmail.com",
    "bumirakha35@gmail.com",
    "fikkydevano119@gmail.com",
    "lesmanadewa831@gmail.com",
    "ilyasafadil23@gmail.com",
    "belindainggridina@gmail.com",
    "putri.bella.14.06.06@gmail.com",
    "meydinamargaretha@gmail.com",
    "muhammadwawan727@gmail.com",
    "budimanyahya71@gmail.com",

    "yahyabudiman72@gmail.com",
    "farhannurrahman92@gmail.com",
    "siscapratiwii62@gmail.com",
    "fiorenahmad4@gmail.com",
    "aliframadhan5098@gmail.com",
    "divanipermatasari@gmail.com",
    "anggadewangga089@gmail.com",
    "putrisasya55@gmail.com",
    "selmanabila30@gmail.com",
    "iwansetyawann4@gmail.com",

    "rafifadhill36@gmail.com",
    "putrajonathan397@gmail.com",
    "karinatauliya@gmail.com",
    "diyastramahendra@gmail.com",
    "agungprastyaa@gmail.com",
    "aulialitahani@gmail.com",
    "sifanadakwurnia@gmail.com",
    "hanisalsabola@gmail.com",
    "denisptrayaa@gmail.com",
    "adelinagriska0@gmail.com",

    "niaaramadhannii@gmail.com",
    "fajarrwijayya@gmail.com",
    "anisshafitrianni@gmail.com",
    "galihhwibowo47@gmail.com",
    "rahhmmaauliaa@gmail.com",
    "mayyadewwii@gmail.com",
    "dhessyylestarii@gmail.com",
    "rizzkyyfirdauss@gmail.com",
    "ditthoprasetyo@gmail.com",
    "amandaaputrrii@gmail.com",

    "kaatiyaaysele0@gmail.com",
    "abhistadeana68@gmail.com",
    "juananoelle123@gmail.com",
    "jasminehaura67@gmail.com",
    "santiawatiaguatina@gmail.com",
    "pawitrisari890@gmail.com",
    "yustifanggraeni6729@gmail.com",
    "pamelaaudine11@gmail.com",
    "anishapranaya976@gmail.com",
    "keitarapramudya@gmail.com",

    "haaacris@gmail.com",
    "sinncta@gmail.com",
    "toocnii@gmail.com",
    "haaabni@gmail.com",
    "ruuucdi@gmail.com",
    "vidipratamah@gmail.com",
    "azzahrafitriana643@gmail.com",
    "ilhammaulanawijaya57@gmail.com",
    "mayyafittriasari@gmail.com",
    "romadon.ramzy@gmail.com",
]

kelaminTaufiq = [
    1,0,1,1,0,1,0,1,0,0,
    0,1,1,0,0,1,1,0,1,1,
    0,1,1,0,1,0,0,0,1,0,
    0,1,0,1,1,0,0,1,1,0,
    1,1,0,1,0,1,0,1,0,0,

    #50
    1,0,0,0,0,1,1,1,0,0,
    0,0,1,0,0,1,0,1,1,0,
    0,0,1,0,0,1,1,1,0,1,
    1,0,1,0,1,1,1,0,0,1,
    1,1,1,1,1,1,1,1,1,1,


    # 100
    0,1,0,1,0,0,1,0,1,0,
]

namaInisial = [
    "Ali Hasanudin",
    "Ydw",
    "Bayu Danang Merta",
    "PW",
    "RS",
    "Ayu Yulistya Ningsih",
    "Rifky Wahyu Saputra",
    "Putra Rudi Wirawan Nurbakti",
    "Putri Keancana",
    "BCA",
    "APW",
    "Rayhan Bagus Ghifari",
    "Raja Putra Wardanawan",
    "AR",
    "Sus",
    "RU",
    "RNS",
    "Fs",
    "PS",
    "FA",
    "Mn",
    "AR",
    "Alffianto Kuntoro",
    "DE",
    "DH",
    "RR",
    "Anggraeni Ratna Safitri",
    "Affifah Rahman Nabila",
    "Putri Kirana Dewi",
    "BS",
    "BS",
    "AM",
    "SA",
    "Kristiani Livia Viadgianti",
    "ARN",
    "BH",
    "MFW",
    "WC",
    "Yuli Ayunda Dewi",
    "DC",
    "YS",
    "Bayu Dwiganara",
    "Mona Hadfinna",
    "Nma",
    "EP",
    "FN",
    "Nanda Marsa Ayunda",
    "M. Irsyad Gunawan Agung",
    "Fattahilah Sadewa",
    "Shaka Kurnia Wijaya",
    "CP",
    "Yoga Syahrul Anugrah",
    "Mutia Ayu Nur",
    "RA",
    "SA",
    "YW",
    "NEY",
    "Cintya Cindy Ayu Nissa",
    "Indah Budi Pratiwi",
    "RR",
    "SAS",
    "Nadilla Carina Fionita",
    "LK",
    "Naufal Akhmal Wijayanto",
    "Nana Annisa",
    "BDM",
    "HAH",
    "RL",
    "AK",
    "Mahendra Rhejaa Fadilah",
    "Sadewa Lingga Budiantoro",
    "NA",
    "Muhammad Iqbal Ramadhan",
    "Arya Perdana Kusuma Wicasa",
    "NA",
    "SK",
    "SM",
    "Yanuar Suryadi",
    "DY",
    "FEN",
    "RPS",
    "MDu",
    "Revan Malik Ibrahim",
    "LA",
    "MPL",
    "SR",
    "EW",
    "Rensky Maulana Ibrahim",
    "BPW",
    "DP",
    "DP",
    "ARN",
    "NSQ",
    "Salma Arowaya",
    "KA",
    "Bella Permata Sari",
    "RAw",
    "JA",
    "DKW",
    "RU",
    "Rasya Gibran Sulistyo",
    "DS",
    "DK",
    "Bagas Putra Ariel",
    "MF",
    "Marshanda Clarista Putri Bianca",
    "PK",
    "BAN",
    "Yahya Nugraha",
    "Septian Andini Fitria",
    "AP",
    "AR",
    "SA",
    "SF",
    "AN",
    "CN",
    "Kayla Naisya Faradila",
    "SN",
    "CAD",
    "Putri Agustina Wahyuni",
    "HG",
    "Zaaka Billy Badrurahman",
    "Annisa Chania",
    "PKW",
    "Bellanda Clara Ayunda ",
    "YS",
    "Sutisna Ayuni",
    "Fikri Budi Ramadhan",
    "Gizella Anastya Syakhira",
    "NIS",
    "DP",
    "SLB",
    "ON",
    "Intan Putri Aprillia",
    "Dp",
    "Achmad Billy Maulana",
    "Attaka Majid",
    "DP",
    "Syifa Radifah",
    "DW",
    "AD",
    "Cynara Nafisah",
    "Fabian Nadeo Putra",
    "AKS",
    "Nayla Chelsea Anggita",
    "Syifa Putri Ramadhani",
    "ABP",
    "BS",
    "AN",
    "M. Putra Susanto",
    "EW",
    "AH",
    "Budi Ahmad Putra Laksa",
    "Fani Cintya A",
    "Reyhan Utomowa",
    "KA",
    "SKW",
    "Budi Suryanto",
    "ADW",
    "DSW",
    "SP",
    "YN",
    "AC",
    "ASP",
    "AN",
    "AG",
    "Rayhan Adi Wicasa",
    "Aryo Nugraha",
    "Rt",
    "FP",
    "YHK",
    "Ap",
    "RA",
    "ON",
    "Aditya Derdinand",
    "Immada Clarissa Putri Anjani",
    "Fryshta Eka Nabilla",
    "Nia EKa Yuliana",
    "AKJ",
    "MDP",
    "AP",
    "MTA",
    "SH",
    "BR",
    "M. Fadil Achmad",
    "DN",
    "Muhammad Nur Faqih Mahmud",
    "RF",
    "Muhammad Gilang Ramadhan",
    "M. Putra Hartanto",
    "Tiara Andini Azzizah",
    "HC",
    "Afifah Renu Hasanah",
    "Jesica Putri Ayu Deviana",
    "Delima Ariesta",
    "AF",
    "Rayhan Cakra Lesmana",
    "Rayhan Ferdinand",
    "EP",
    "RPW",
    "NS",
    "Fadhil Achmad Saputro",
    "NA",
    "Miranda Nella",
    "YN",
    "RFP",
    "YP",
    "Mustofa Daniel Arya",
    "Riskia Ayu Febrianti",
    "MD",
    "Yudi Pradanawan",
    "Aldi Maulana Akbar",
    "DR",
    "Cilla Cintya Chania",
    "IK",
    "Paradista Chania Aysala",
    "NA",
    "Siti Fauziyah",
    "Famelya Anggita Novianti",
    "RAS",
    "RA",
    "BD",
    "Reno Naufal Wijaya",
    "Azzarin Ristia Nabila",
    "BS",
    "Mikha Ilyasa Agung",
    "Diah Ayu Cindy",
    "AM",
    "RN",
    "Bella Nur Rahma",
    "RP",
    "TD",
    "FNP",
    "BSP",
    "IA",
    "Angga Siregar Putra",
    "MH",
    "RA",
    "Adriansyah Qolbi Muhammad",
    "PA",
    "Budi Prasetyo Wibowo",
    "Siti Rahma Aulia Sarah",
    "DAC",
    "Safa Fitri Aulia",
    "Muhammad Septyo Agung Mahmud",
    "FN",
    "YAD",
    "Franky Kusuma Adelardo",
    "MRF",
    "AS",

    "Dwi Nugroho Santoso",
    "AU",
    "Anisa Cahaya Putri",
    "Dika Kurniawan",
    "DKS",
    "Laila Rachmawati",
    "Rizky Putri Ramadhani",
    "Citra Permata Dewi",
    "AJN",
    "Muhammad Iqbal Pratama",
    "LP",
    "Aditya Wahyudi",
    "RCD",
    "Fitriani Sari Dewi",
    "Yoga Aditya Saputra",
    "MIP",
    "FSR",
    "AB",
    "Rina Amelia Pangestu",
    "Dian Purnama Sari",
    "YAS",
    "Siti Nurul Aisyah",
    "Farhan Maulana Putra",
    "DR",
    "Agung Wijaya Kusuma",
]

kelaminInisial = [
    0,0,0,1,1,1,0,0,1,1,1,0,0,1,1,0,0,0,1,0,
    1,0,0,1,1,0,1,1,1,0,0,1,1,1,0,1,0,0,1,1,
    1,0,1,1,1,0,1,0,0,0,0,0,1,1,1,1,1,1,1,0,
    1,1,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,
    0,1,0,0,0,0,1,0,0,0,0,1,1,1,1,1,0,0,1,0,
    0,1,1,0,1,1,1,0,0,1,0,0,1,1,1,1,1,1,1,1,
    0,0,1,0,1,1,0,0,1,1,0,1,1,1,1,0,0,0,1,1,
    1,1,0,0,1,1,1,0,0,0,0,0,0,1,0,0,0,0,0,1,
    1,0,1,0,0,1,0,0,0,0,1,0,1,0,0,1,1,1,1,1,
    1,1,1,1,0,0,0,0,0,0,1,0,1,1,1,1,0,0,1,0,
    0,0,0,1,1,0,0,0,1,0,0,0,1,1,0,1,0,1,1,0,
    1,0,0,1,0,0,1,1,1,1,1,0,0,1,0,0,0,0,0,0,
    0,1,0,1,0,0,1,0,1,1,
    0,0,1,0,0,1,1,1,1,0,0,0,1,1,0,1,1,1,1,1,
    0,1,0,0,0,
]

inisialPerempuan = [
    "Ydw",
    "PW",
    "RS",
    "BCA",
    "APW",
    "AR",
    "Sus",
    "RU",
    "RNS",
    "Fs",

    "PS",
    "FA",
    "Mn",
    "AR",
    "DE",
    "DH",
    "RR",
    "BS",
    "BS",
    "AM",

    "SA",
    "ARN",
    "BH",
    "MFW",
    "WC",
    "DC",
    "YS",
    "Nma",
    "EP",
    "FN",

    "CP",
    "RA",
    "SA",
    "YW",
    "NEY",
    "RR",
    "SAS",
    "LK",
    "BDM",
    "HAH",

    "RL",
    "AK",
    "NA",
    "NA",
    "SK",
    "SM",
    "DY",
    "FEN",
    "RPS",
    "MDu",

    "LA",
    "MPL",
    "SR",
    "EW",
    "BPW",
    "DP",
    "DP",
    "ARN",
    "NSQ",
    "KA",

    "RAw",
    "JA",
    "DKW",
    "RU",
    "DS",
    "DK",
    "MF",
    "PK",
    "BAN",
    "AP",

    "AR",
    "SA",
    "SF",
    "AN",
    "CN",
    "SN",
    "CAD",
    "HG",
    "PKW",
    "YS",

    "NIS",
    "DP",
    "SLB",
    "ON",
    "Dp",
    "DP",
    "DW",
    "AD",
    "AKS",
    "ABP",

    "BS",
    "AN",
    "EW",
    "AH",
    "KA",
    "SKW",
    "ADW",
    "DSW",
    "SP",
    "YN",

    "AC",
    "ASP",
    "AN",
    "AG",
    "Rt",
    "FP",
    "YHK",
    "Ap",
    "RA",
    "ON",

    "AKJ",
    "MDP",
    "AP",
    "MTA",
    "SH",
    "BR",
    "DN",
    "RF",
    "HC",
    "AF",

    "EP",
    "RPW",
    "NS",
    "NA",
    "YN",
    "RFP",
    "YP",
    "MD",
    "DR",
    "IK",

    "NA",
    "RAS",
    "RA",
    "BD",
    "BS",
    "AM",
    "RN",
    "RP",
    "TD",
    "FNP",

    "BSP",
    "IA",
    "Angga Siregar Putra",
    "MH",
    "RA",
    "Adriansyah Qolbi Muhammad",
    "PA",
    "Budi Prasetyo Wibowo",
    "Siti Rahma Aulia Sarah",
    "DAC",
    "Safa Fitri Aulia",
    "Muhammad Septyo Agung Mahmud",
    "FN",
    "YAD",
    "Franky Kusuma Adelardo",
    "MRF",
    "AS",

    "Dwi Nugroho Santoso",
    "AU",
    "Anisa Cahaya Putri",
    "Dika Kurniawan",
    "DKS",
    "Laila Rachmawati",
    "Rizky Putri Ramadhani",
    "Citra Permata Dewi",
    "AJN",
    "Muhammad Iqbal Pratama",
    "LP",
    "RCD",
    "MIP",
    "FSR",
    "AB",
    "YAS",
    "DR",
]
